pdf_beamtime_server:
  ros__parameters:
    home_angles: [-0.11536, -1.783732, 0.38816, -1.75492, 0.11484, 3.14159] #For real robot
    pickup_approach_angles: [4.089481, -0.987856, 2.167873, -1.174083, 0.899019, 3.141593]
    gripper_present: true
    joint_acc_vel_scaling_factor: 0.1
